In [1]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFiles and folders here:")
print(os.listdir())

Current folder:
/Users/adityabohra/Desktop/credit risk portfolio

Files and folders here:
['raw:data', '.DS_Store', '.ipynb_checkpoints', '01_understand_data.ipynb']

In [2]:
import os

print(os.listdir("raw:data"))

['credit_risk_dataset.csv']

In [5]:
import pandas as pd

df = pd.read_csv("raw:data/credit_risk_dataset.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [6]:
print("Dataset dimensions:", df.shape)

Dataset dimensions: (32581, 12)

In [7]:
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [8]:
df.columns.tolist()

['person_age',
 'person_income',
 'person_home_ownership',
 'person_emp_length',
 'loan_intent',
 'loan_grade',
 'loan_amnt',
 'loan_int_rate',
 'loan_status',
 'loan_percent_income',
 'cb_person_default_on_file',
 'cb_person_cred_hist_length']

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  str
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  str
 5   loan_grade                  32581 non-null  str
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  str
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), str(4)
memory usage: 3.5 MB

In [10]:
df[df["loan_int_rate"].isna()].head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
39,23,71500,RENT,3.0,DEBTCONSOLIDATION,D,30000,NaN,1,0.42,N,4
50,24,78000,RENT,4.0,DEBTCONSOLIDATION,D,30000,NaN,1,0.38,Y,4
57,23,277000,OWN,3.0,PERSONAL,A,35000,NaN,0,0.13,N,4
59,24,12000,OWN,2.0,VENTURE,E,1750,NaN,0,0.15,Y,3
62,26,263000,MORTGAGE,0.0,EDUCATION,B,10000,NaN,1,0.04,N,4

In [11]:
df["loan_int_rate"].isna().sum()

np.int64(3116)

In [12]:
df.isna().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [13]:
df.isna().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [14]:
df["loan_status"].value_counts()

loan_status
0    25473
1     7108
Name: count, dtype: int64

In [15]:
df.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [16]:
# Count records where the person's age is above 100
print("Records with age above 100:")
print((df["person_age"] > 100).sum())

# Display some matching records for investigation
df.loc[
    df["person_age"] > 100,
    ["person_age", "person_income", "person_emp_length", "loan_status"]
].head(10)

Records with age above 100:
5

       person_age  person_income  person_emp_length  loan_status
81            144         250000                4.0            0
183           144         200000                4.0            0
575           123          80004                2.0            0
747           123          78000                7.0            0
32297         144        6000000               12.0            0

In [17]:
df.loc[
    df["person_age"] > 100,
    ["person_age", "loan_status"]
]

       person_age  loan_status
81            144            0
183           144            0
575           123            0
747           123            0
32297         144            0

In [18]:
df.loc[
    df["person_emp_length"] > 50,
    ["person_age", "person_emp_length", "person_income", "loan_status"]
]

     person_age  person_emp_length  person_income  loan_status
0            22              123.0          59000            1
210          21              123.0         192000            0

# Check records where employment length exceeds age
df.loc[
    df["person_emp_length"] > df["person_age"],
    ["person_age", "person_emp_length", "person_income", "loan_status"]
]


## Initial Data Quality Observations

### 1. Missing Values
- `person_emp_length`: 895 missing values.
- `loan_int_rate`: 3,116 missing values.
- Decision: Handling method not yet decided.

### 2. Unusually High Ages
- Column: `person_age`
- Observation: 5 records have age above 100; values include 123 and 144.
- Status: Requires investigation before deciding whether to retain or exclude these records.

### 3. Employment Length Inconsistency
- Columns: `person_age`, `person_emp_length`
- Observation: 2 records have employment length of 123 years, while recorded ages are 21 and 22.
- Status: Potential data-quality issue; verify before making changes.

### Data Preservation
- Original CSV remains unchanged.
- No records have been deleted or modified.
- Cleaning decisions will be documented with their rationale.

In [21]:
df.duplicated().sum()

np.int64(165)

In [22]:
duplicate_rows = df[df.duplicated(keep=False)]

display(duplicate_rows.head(10))

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
14,23,115000,RENT,2.0,EDUCATION,A,35000,7.90,0,0.30,N,4
238,22,183000,MORTGAGE,3.0,EDUCATION,A,1000,NaN,0,0.01,N,2
252,24,85000,RENT,5.0,MEDICAL,B,25000,10.62,0,0.29,N,4
591,26,20000,MORTGAGE,5.0,MEDICAL,A,4800,5.99,0,0.24,N,3
740,21,21600,OWN,NaN,VENTURE,A,7125,6.99,0,0.33,N,3
817,22,22000,OWN,1.0,DEBTCONSOLIDATION,D,8500,15.05,0,0.39,N,4
920,26,50000,RENT,10.0,PERSONAL,B,18950,NaN,1,0.38,N,3
1094,22,24449,OWN,2.0,VENTURE,B,1800,11.89,0,0.07,N,4
1142,25,60000,RENT,3.0,PERSONAL,A,17000,6.91,0,0.28,N,2
1453,23,20400,RENT,2.0,MEDICAL,A,1200,7.90,0,0.06,N,2

In [23]:
duplicate_rows = df[df.duplicated(keep=False)]

duplicate_rows = duplicate_rows.sort_values(
    by=df.columns.tolist()
)

display(duplicate_rows.head(20))

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
15944,21,8088,RENT,NaN,MEDICAL,C,1200,15.23,0,0.15,Y,2
16835,21,8088,RENT,NaN,MEDICAL,C,1200,15.23,0,0.15,Y,2
2431,21,15600,RENT,0.0,MEDICAL,A,2800,7.40,1,0.18,N,4
17758,21,15600,RENT,0.0,MEDICAL,A,2800,7.40,1,0.18,N,4
2498,21,18000,RENT,0.0,DEBTCONSOLIDATION,A,3000,7.90,1,0.17,N,2
17601,21,18000,RENT,0.0,DEBTCONSOLIDATION,A,3000,7.90,1,0.17,N,2
1778,21,20000,RENT,0.0,MEDICAL,A,2000,NaN,0,0.10,N,3
17642,21,20000,RENT,0.0,MEDICAL,A,2000,NaN,0,0.10,N,3
740,21,21600,OWN,NaN,VENTURE,A,7125,6.99,0,0.33,N,3
17283,21,21600,OWN,NaN,VENTURE,A,7125,6.99,0,0.33,N,3
6191,21,26000,RENT,5.0,DEBTCONSOLIDATION,A,6000,7.49,0,0.23,N,2
16440,21,26000,RENT,5.0,DEBTCONSOLIDATION,A,6000,7.49,0,0.23,N,2
4344,21,26400,RENT,5.0,PERSONAL,C,4750,12.23,0,0.18,N,3
16587,21,26400,RENT,5.0,PERSONAL,C,4750,12.23,0,0.18,N,3
8206,21,27600,RENT,4.0,EDUCATION,A,7500,6.76,0,0.27,N,4
16070,21,27600,RENT,4.0,EDUCATION,A,7500,6.76,0,0.27,N,4
1675,21,28692,MORTGAGE,5.0,EDUCATION,B,3000,10.75,0,0.10,N,2
17144,21,28692,MORTGAGE,5.0,EDUCATION,B,3000,10.75,0,0.10,N,2
13711,21,33009,OWN,5.0,VENTURE,B,12000,11.48,0,0.36,N,4
16864,21,33009,OWN,5.0,VENTURE,B,12000,11.48,0,0.36,N,4

In [24]:
# Create a separate working copy and remove exact duplicate rows
df_clean = df.drop_duplicates().copy()

print("Original rows:", len(df))
print("Rows after removing duplicates:", len(df_clean))
print("Rows removed:", len(df) - len(df_clean))

Original rows: 32581
Rows after removing duplicates: 32416
Rows removed: 165

In [25]:
missing_counts = df_clean.isna().sum()

print(missing_counts[missing_counts > 0])

person_emp_length     887
loan_int_rate        3095
dtype: int64

In [26]:
# Create a separate working copy
df_analysis = df_clean.copy()

# Identify suspicious values before changing anything
invalid_age = df_analysis["person_age"] > 100
invalid_emp_length = (
    df_analysis["person_emp_length"] > df_analysis["person_age"]
)

print("Invalid ages:", invalid_age.sum())
print("Invalid employment lengths:", invalid_emp_length.sum())

# Mark invalid values as missing, preserving the rest of each record
df_analysis.loc[invalid_age, "person_age"] = pd.NA
df_analysis.loc[invalid_emp_length, "person_emp_length"] = pd.NA

# Check updated missing-value counts
print("\nMissing values after cleaning:")
print(df_analysis.isna().sum()[lambda x: x > 0])

print("\nRows available for analysis:", len(df_analysis))

Invalid ages: 5
Invalid employment lengths: 2

Missing values after cleaning:
person_age              5
person_emp_length     889
loan_int_rate        3095
dtype: int64

Rows available for analysis: 32416

In [27]:
df_analysis["person_emp_length"].median()

np.float64(4.0)

In [28]:
# Fill missing employment lengths with the median
emp_median = df_analysis["person_emp_length"].median()

df_analysis["person_emp_length"] = (
    df_analysis["person_emp_length"].fillna(emp_median)
)

# Verify
print("Missing employment lengths:",
      df_analysis["person_emp_length"].isna().sum())

Missing employment lengths: 0

In [29]:
# Calculate the median interest rate
rate_median = df_analysis["loan_int_rate"].median()

# Fill missing interest rates with their median
df_analysis["loan_int_rate"] = (
    df_analysis["loan_int_rate"].fillna(rate_median)
)

# Check remaining missing values
print(df_analysis.isna().sum()[df_analysis.isna().sum() > 0])

person_age    5
dtype: int64

In [30]:
# Remove rows with missing ages
df_analysis = df_analysis.dropna(subset=["person_age"]).copy()

# Verify the result
print("Final dataset shape:", df_analysis.shape)
print("Missing ages:", df_analysis["person_age"].isna().sum())
print("Total missing values:", df_analysis.isna().sum().sum())

Final dataset shape: (32411, 12)
Missing ages: 0
Total missing values: 0

In [31]:
# 1. Check missing values in each column
print("Missing values per column:")
print(df_analysis.isna().sum())

# 2. Check total missing values
print("\nTotal missing values:", df_analysis.isna().sum().sum())

# 3. Check duplicate rows
print("Duplicate rows:", df_analysis.duplicated().sum())

# 4. Check dataset dimensions
print("Dataset shape:", df_analysis.shape)

Missing values per column:
person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64

Total missing values: 0
Duplicate rows: 0
Dataset shape: (32411, 12)

In [32]:
# View the cleaned dataset
display(df_analysis.head())

# Check data types and non-null counts
df_analysis.info()

# Examine numerical columns
display(df_analysis.describe())

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22.0,59000,RENT,4.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21.0,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25.0,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23.0,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24.0,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

<class 'pandas.DataFrame'>
Index: 32411 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32411 non-null  float64
 1   person_income               32411 non-null  int64
 2   person_home_ownership       32411 non-null  str
 3   person_emp_length           32411 non-null  float64
 4   loan_intent                 32411 non-null  str
 5   loan_grade                  32411 non-null  str
 6   loan_amnt                   32411 non-null  int64
 7   loan_int_rate               32411 non-null  float64
 8   loan_status                 32411 non-null  int64
 9   loan_percent_income         32411 non-null  float64
 10  cb_person_default_on_file   32411 non-null  str
 11  cb_person_cred_hist_length  32411 non-null  int64
dtypes: float64(4), int64(4), str(4)
memory usage: 3.8 MB

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32411.000000,3.241100e+04,32411.000000,32411.000000,32411.000000,32411.000000,32411.000000,32411.000000
mean,27.730369,6.589796e+04,4.761377,9593.591682,11.014528,0.218722,0.170259,5.811052
std,6.210448,5.252093e+04,3.983639,6322.529723,3.083234,0.413386,0.106808,4.057816
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,8.490000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12250.000000,13.110000,0.000000,0.230000,8.000000
max,94.000000,2.039784e+06,41.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [33]:
# Count borrowers in each loan status
print(df_analysis["loan_status"].value_counts())

# Calculate the percentage in each loan status
print(
    (df_analysis["loan_status"].value_counts(normalize=True) * 100)
    .round(2)
)

loan_status
0    25322
1     7089
Name: count, dtype: int64
loan_status
0    78.13
1    21.87
Name: proportion, dtype: float64

In [34]:
grade_default_rate = (
    df_analysis.groupby("loan_grade")["loan_status"]
    .mean()
    .mul(100)
    .round(2)
    .sort_values(ascending=False)
)

print(grade_default_rate)

loan_grade
G    98.44
F    70.54
E    64.49
D    59.06
C    20.76
B    16.32
A     9.96
Name: loan_status, dtype: float64

In [35]:
grade_summary = (
    df_analysis.groupby("loan_grade")
    .agg(
        total_loans=("loan_status", "count"),
        defaults=("loan_status", "sum"),
        default_rate=("loan_status", "mean")
    )
)

grade_summary["default_rate"] = (
    grade_summary["default_rate"] * 100
).round(2)

print(grade_summary.sort_values("default_rate", ascending=False))

            total_loans  defaults  default_rate
loan_grade
G                    64        63         98.44
F                   241       170         70.54
E                   963       621         64.49
D                  3620      2138         59.06
C                  6436      1336         20.76
B                 10384      1695         16.32
A                 10703      1066          9.96

In [36]:
df_analysis["income_group"] = pd.qcut(
    df_analysis["person_income"],
    q=4,
    labels=["Low", "Medium", "High", "Very High"]
)

income_summary = (
    df_analysis.groupby("income_group", observed=True)
    .agg(
        total_loans=("loan_status", "count"),
        defaults=("loan_status", "sum"),
        default_rate=("loan_status", "mean")
    )
)

income_summary["default_rate"] = (
    income_summary["default_rate"] * 100
).round(2)

print(income_summary)

              total_loans  defaults  default_rate
income_group
Low                  8104      3221         39.75
Medium               8188      1753         21.41
High                 8019      1375         17.15
Very High            8100       740          9.14

In [37]:
df_analysis["loan_amount_group"] = pd.qcut(
    df_analysis["loan_amnt"],
    q=4,
    labels=["Low", "Medium", "High", "Very High"],
    duplicates="drop"
)

loan_amount_summary = (
    df_analysis.groupby("loan_amount_group", observed=True)
    .agg(
        total_loans=("loan_status", "count"),
        defaults=("loan_status", "sum"),
        default_rate=("loan_status", "mean")
    )
)

loan_amount_summary["default_rate"] = (
    loan_amount_summary["default_rate"] * 100
).round(2)

print(loan_amount_summary)

                   total_loans  defaults  default_rate
loan_amount_group
Low                       9428      1930         20.47
Medium                    7281      1216         16.70
High                      7642      1542         20.18
Very High                 8060      2401         29.79

In [38]:
ratio_summary = (
    df_analysis.groupby("loan_percent_income")
    ["loan_status"]
    .mean()
    .mul(100)
    .round(2)
    .sort_index()
)

print(ratio_summary)

loan_percent_income
0.00      0.00
0.01      5.80
0.02      8.97
0.03      9.70
0.04     12.27
         ...
0.72    100.00
0.76    100.00
0.77    100.00
0.78    100.00
0.83      0.00
Name: loan_status, Length: 77, dtype: float64

In [39]:
# Create loan-to-income ratio bands
df_analysis["loan_income_band"] = pd.cut(
    df_analysis["loan_percent_income"],
    bins=[-0.01, 0.10, 0.20, 0.30, 0.40, 1.00],
    labels=["0-10%", "10-20%", "20-30%", "30-40%", "40%+"]
)

# Calculate default statistics for each band
ratio_band_summary = (
    df_analysis.groupby("loan_income_band", observed=True)
    .agg(
        total_loans=("loan_status", "count"),
        defaults=("loan_status", "sum"),
        default_rate=("loan_status", "mean")
    )
)

# Convert default rate to percentage
ratio_band_summary["default_rate"] = (
    ratio_band_summary["default_rate"] * 100
).round(2)

print(ratio_band_summary)

                  total_loans  defaults  default_rate
loan_income_band
0-10%                   10427      1226         11.76
10-20%                  11999      1815         15.13
20-30%                   6166      1358         22.02
30-40%                   2700      1860         68.89
40%+                     1119       830         74.17

In [40]:
df_analysis["interest_rate_band"] = pd.cut(
    df_analysis["loan_int_rate"],
    bins=[0, 8, 12, 16, 20, 30],
    labels=["0–8%", "8–12%", "12–16%", "16–20%", "20%+"]
)

interest_summary = (
    df_analysis.groupby("interest_rate_band", observed=True)
    .agg(
        total_loans=("loan_status", "count"),
        defaults=("loan_status", "sum"),
        default_rate=("loan_status", "mean")
    )
)

interest_summary["default_rate"] = (
    interest_summary["default_rate"] * 100
).round(2)

print(interest_summary)

                    total_loans  defaults  default_rate
interest_rate_band
0–8%                       7906       737          9.32
8–12%                     13391      2274         16.98
12–16%                     9342      2963         31.72
16–20%                     1698      1052         61.96
20%+                         74        63         85.14

In [41]:
df_analysis["employment_group"] = pd.cut(
    df_analysis["person_emp_length"],
    bins=[-1, 2, 5, 10, 50],
    labels=["0–2 years", "3–5 years", "6–10 years", "10+ years"]
)

employment_summary = (
    df_analysis.groupby("employment_group", observed=True)
    .agg(
        total_loans=("loan_status", "count"),
        defaults=("loan_status", "sum"),
        default_rate=("loan_status", "mean")
    )
)

employment_summary["default_rate"] = (
    employment_summary["default_rate"] * 100
).round(2)

print(employment_summary)

                  total_loans  defaults  default_rate
employment_group
0–2 years               10814      2933         27.12
3–5 years               10118      2133         21.08
6–10 years               8564      1550         18.10
10+ years                2915       473         16.23

In [42]:
df_analysis["credit_history_group"] = pd.cut(
    df_analysis["cb_person_cred_hist_length"],
    bins=[-1, 2, 5, 10, 20, 100],
    labels=["0–2 years", "3–5 years", "6–10 years",
            "11–20 years", "20+ years"]
)

credit_history_summary = (
    df_analysis.groupby("credit_history_group", observed=True)
    .agg(
        total_loans=("loan_status", "count"),
        defaults=("loan_status", "sum"),
        default_rate=("loan_status", "mean")
    )
)

credit_history_summary["default_rate"] = (
    credit_history_summary["default_rate"] * 100
).round(2)

print(credit_history_summary)

                      total_loans  defaults  default_rate
credit_history_group
0–2 years                    5924      1404         23.70
3–5 years                   13658      3024         22.14
6–10 years                   9374      1936         20.65
11–20 years                  3243       670         20.66
20+ years                     212        55         25.94

In [43]:
df_analysis.to_csv("credit_risk_cleaned.csv", index=False)

In [44]:
import os

print(os.getcwd())

/Users/adityabohra/Desktop/credit risk portfolio

In [45]:
import os

print(os.path.exists("credit_risk_cleaned.csv"))
print(os.path.abspath("credit_risk_cleaned.csv"))

True
/Users/adityabohra/Desktop/credit risk portfolio /credit_risk_cleaned.csv

In [1]:
df_analysis.to_csv(
    "credit_risk_cleaned_import.csv",
    index=False,
    encoding="utf-8-sig"
)

NameError: name 'df_analysis' is not defined

In [2]:
%whos

Variable               Type        Data/Info
--------------------------------------------
dataframe_columns      function    <function dataframe_columns at 0x104fb3c10>
dataframe_hash         function    <function dataframe_hash at 0x104fb3ab0>
dtypes_str             function    <function dtypes_str at 0x104fb3ed0>
get_dataframes         function    <function get_dataframes at 0x14d915f30>
getpass                module      <module 'getpass' from '/<...>b/python3.14/getpass.py'>
hashlib                module      <module 'hashlib' from '/<...>b/python3.14/hashlib.py'>
import_pandas_safely   function    <function import_pandas_safely at 0x14dc46a30>
is_data_frame          function    <function is_data_frame at 0x14dc46ae0>
json                   module      <module 'json' from '/opt<...>on3.14/json/__init__.py'>

In [3]:
import pandas as pd

df_analysis = pd.read_csv("credit_risk_cleaned.csv")

print(df_analysis.shape)
df_analysis.head()

(32411, 18)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,income_group,loan_amount_group,loan_income_band,interest_rate_band,employment_group,credit_history_group
0,22.0,59000,RENT,4.0,PERSONAL,D,35000,16.02,1,0.59,Y,3,High,Very High,40%+,16–20%,3–5 years,3–5 years
1,21.0,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2,Low,Low,0-10%,8–12%,3–5 years,0–2 years
2,25.0,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3,Low,Medium,40%+,12–16%,0–2 years,3–5 years
3,23.0,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2,High,Very High,40%+,12–16%,3–5 years,0–2 years
4,24.0,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4,Medium,Very High,40%+,12–16%,6–10 years,3–5 years

In [4]:
df_analysis.to_csv(
    "credit_risk_cleaned_import.csv",
    index=False,
    encoding="utf-8-sig"
)

In [5]:
import importlib.util

for package in ["sqlalchemy", "pymysql", "mysql"]:
    print(package, importlib.util.find_spec(package) is not None)

sqlalchemy True
pymysql False
mysql False

In [6]:
%pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import sqlalchemy
import pymysql

df_analysis = pd.read_csv("credit_risk_cleaned.csv")

print("Packages ready!")
print("Dataset shape:", df_analysis.shape)

Packages ready!
Dataset shape: (32411, 18)

In [2]:
from sqlalchemy import create_engine
from getpass import getpass

# Enter your MySQL root password privately
mysql_password = getpass("Enter your MySQL root password: ")

# Connect to the credit_risk database on your Mac
engine = create_engine(
    "mysql+pymysql://root:" + mysql_password + "@localhost:3306/credit_risk"
)

# Test the connection
with engine.connect() as connection:
    print("Successfully connected to MySQL!")

Enter your MySQL root password:  ········

Successfully connected to MySQL!

In [3]:
df_analysis.to_sql(
    name="loan_data",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=1000
)

32411